import collections.abc
from typing import Callable, ClassVar, overload

class ETVData:
    M0_epoch: float
    def __init__(self, filename: str, units: str = ..., skip: int = ..., max_rows: int = ..., delimiter: str = ...) -> None: ...
    @property
    def N(self) -> int: ...
    @property
    def datafile(self) -> str: ...
    @property
    def epochs(self) -> list[float]: ...
    @property
    def et(self) -> list[float]: ...
    @property
    def etsig(self) -> list[float]: ...

class GAIAdata:
    M0_epoch: float
    def __init__(self, filename: str, units: str = ..., skip: int = ..., max_rows: int = ..., delimiter: str = ...) -> None: ...
    @property
    def N(self) -> int: ...
    @property
    def datafile(self) -> str: ...
    @property
    def pf(self) -> list[float]: ...
    @property
    def psi(self) -> list[float]: ...
    @property
    def t(self) -> list[float]: ...
    @property
    def units(self) -> str: ...
    @property
    def w(self) -> list[float]: ...
    @property
    def wsig(self) -> list[float]: ...

class HGPMdata:
    plot: ClassVar[Callable] = ...
    def __init__(self, gaia_id: int) -> None: ...
    @property
    def chisq(self): ...
    @property
    def epoch_dec_gaia(self) -> float: ...
    @property
    def epoch_dec_hip(self) -> float: ...
    @property
    def epoch_ra_gaia(self) -> float: ...
    @property
    def epoch_ra_hip(self) -> float: ...
    @property
    def gaia_id(self) -> int: ...
    @property
    def parallax_gaia(self) -> float: ...
    @property
    def parallax_gaia_error(self) -> float: ...
    @property
    def pm_dec_gaia(self) -> float: ...
    @property
    def pm_dec_hg(self) -> float: ...
    @property
    def pm_dec_hip(self) -> float: ...
    @property
    def pm_ra_gaia(self) -> float: ...
    @property
    def pm_ra_hg(self) -> float: ...
    @property
    def pm_ra_hip(self) -> float: ...
    @property
    def rho_gaia(self): ...
    @property
    def rho_hg(self): ...
    @property
    def rho_hip(self): ...
    @property
    def sig_gaia_dec(self): ...
    @property
    def sig_gaia_ra(self): ...
    @property
    def sig_hg_dec(self): ...
    @property
    def sig_hg_ra(self): ...
    @property
    def sig_hip_dec(self): ...
    @property
    def sig_hip_ra(self): ...

class PHOTdata:
    def __init__(self, filename: str, skip: int = ..., delimiter: str = ...) -> None: ...
    @property
    def N(self) -> int: ...
    @property
    def sig(self) -> list[float]: ...
    @property
    def t(self) -> list[float]: ...
    @property
    def y(self) -> list[float]: ...

class RVData:
    plot: ClassVar[Callable] = ...
    M0_epoch: float
    double_lined: bool
    indicator_names: list[str]
    instrument: str
    instruments: list[str]
    trend_epoch: float
    @overload
    def __init__(self, filenames: collections.abc.Sequence[str], units: str = ..., skip: int = ..., max_rows: int = ..., delimiter: str = ..., indicators: collections.abc.Sequence[str] = ..., double_lined: bool = ...) -> None: ...
    @overload
    def __init__(self, filename: str, units: str = ..., skip: int = ..., max_rows: int = ..., multi: bool = ..., delimiter: str = ..., indicators: collections.abc.Sequence[str] = ..., double_lined: bool = ...) -> None: ...
    @overload
    def __init__(self, t: collections.abc.Sequence[float], y: collections.abc.Sequence[float], sig: collections.abc.Sequence[float], units: str = ..., instrument: str = ...) -> None: ...
    @overload
    def __init__(self, t: collections.abc.Sequence[collections.abc.Sequence[float]], y: collections.abc.Sequence[collections.abc.Sequence[float]], sig: collections.abc.Sequence[collections.abc.Sequence[float]], units: str = ..., instruments: collections.abc.Sequence[str] = ...) -> None: ...
    def get_RV_max(self) -> float: ...
    def get_RV_mean(self) -> float: ...
    def get_RV_min(self) -> float: ...
    def get_RV_span(self) -> float: ...
    def get_RV_std(self) -> float: ...
    def get_RV_var(self) -> float: ...
    def get_max_RV_span(self) -> float: ...
    def get_t_max(self) -> float: ...
    def get_t_middle(self) -> float: ...
    def get_t_min(self) -> float: ...
    def get_timespan(self) -> float: ...
    def get_trend_magnitude(self, *args, **kwargs): ...
    def get_unique_t(self) -> list[float]: ...
    def load(self, filename: str, units: str, skip: int, max_rows: int, delimiter: str, indicators: collections.abc.Sequence[str]) -> None: ...
    def topslope(self) -> float: ...
    @property
    def N(self) -> int: ...
    @property
    def actind(self) -> list[list[float]]: ...
    @property
    def datafile(self) -> str: ...
    @property
    def datafiles(self) -> list[str]: ...
    @property
    def multi(self) -> bool: ...
    @property
    def normalized_actind(self) -> list[list[float]]: ...
    @property
    def obsi(self) -> list[int]: ...
    @property
    def sig(self) -> list[float]: ...
    @property
    def sig2(self) -> list[float]: ...
    @property
    def skip(self) -> int: ...
    @property
    def t(self) -> list[float]: ...
    @property
    def units(self) -> str: ...
    @property
    def y(self) -> list[float]: ...
    @property
    def y2(self) -> list[float]: ...

class loadtxt:
    def __init__(self, *args, **kwargs) -> None: ...
    def comments(self, *args, **kwargs): ...
    def delimiters(self, *args, **kwargs): ...
    def max_errors(self, *args, **kwargs): ...
    def max_rows(self, *args, **kwargs): ...
    def skiprows(self, *args, **kwargs): ...
    def usecols(self, *args, **kwargs): ...
    def __call__(self) -> list[list[float]]: ...
