import collections.abc
from _typeshed import Incomplete
from typing import overload

class BivariateGaussian(Distribution):
    mean_x: Incomplete
    mean_y: Incomplete
    rho: Incomplete
    sigma_x: Incomplete
    sigma_y: Incomplete
    def __init__(self, mean_x: float, mean_y: float, sigma_x: float, sigma_y: float, rho: float) -> None: ...
    def logpdf(self, x: float, y: float) -> float: ...

class Cauchy(Distribution):
    loc: float
    scale: float
    def __init__(self, loc: float, scale: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class Distribution:
    def __init__(self, *args, **kwargs) -> None: ...

class Exponential(Distribution):
    def __init__(self, scale: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def scale(self): ...

class ExponentialRayleighMixture(Distribution):
    scale: Incomplete
    sigma: Incomplete
    weight: Incomplete
    def __init__(self, weight: float, scale: float, sigma: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class Fixed(Distribution):
    val: float
    def __init__(self, value: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class Gaussian(Distribution):
    loc: float
    scale: float
    def __init__(self, loc: float, scale: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class GaussianMixture(Distribution):
    @overload
    def __init__(self, means: collections.abc.Sequence[float], sigmas: collections.abc.Sequence[float]) -> None: ...
    @overload
    def __init__(self, means: collections.abc.Sequence[float], sigmas: collections.abc.Sequence[float], lower: float, upper: float) -> None: ...
    @overload
    def __init__(self, means: collections.abc.Sequence[float], sigmas: collections.abc.Sequence[float], weights: collections.abc.Sequence[float], lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class HalfGaussian(Distribution):
    scale: float
    def __init__(self, scale: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class InverseGamma(Distribution):
    alpha: float
    beta: float
    def __init__(self, alpha: float, beta: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class InverseMoment(Distribution):
    kmax: Incomplete
    tau: Incomplete
    def __init__(self, tau: float, kmax: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class Kumaraswamy(Distribution):
    a: Incomplete
    b: Incomplete
    def __init__(self, a: float, b: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class Laplace(Distribution):
    loc: float
    scale: float
    def __init__(self, loc: float, scale: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class LogUniform(Distribution):
    def __init__(self, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def lower(self): ...
    @property
    def upper(self): ...

class ModifiedLogUniform(Distribution):
    def __init__(self, knee: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def knee(self): ...
    @property
    def upper(self): ...

class Pareto(Distribution):
    def __init__(self, min: float, alpha: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class RNG:
    def __init__(self, seed: int) -> None: ...
    def rand(self) -> float: ...
    def rand_int(self, *args, **kwargs): ...

class Rayleigh(Distribution):
    scale: Incomplete
    def __init__(self, scale: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class Sine(Distribution):
    def __init__(self) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class SingleTransitPeriodPrior(Distribution):
    def __init__(self, W: float, L: float, Pmax: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def L(self) -> float: ...
    @property
    def Pmax(self) -> float: ...
    @property
    def W(self) -> float: ...

class Triangular(Distribution):
    center: Incomplete
    lower: Incomplete
    upper: Incomplete
    def __init__(self, lower: float, center: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class TruncatedCauchy(Distribution):
    def __init__(self, loc: float, scale: float, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def loc(self) -> float: ...
    @property
    def lower(self): ...
    @property
    def scale(self) -> float: ...
    @property
    def upper(self): ...

class TruncatedExponential(Distribution):
    def __init__(self, scale: float, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def lower(self): ...
    @property
    def scale(self): ...
    @property
    def upper(self): ...

class TruncatedGaussian(Distribution):
    def __init__(self, loc: float, scale: float, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def loc(self) -> float: ...
    @property
    def lower(self) -> float: ...
    @property
    def scale(self) -> float: ...
    @property
    def upper(self) -> float: ...

class TruncatedPareto(Distribution):
    def __init__(self, min: float, alpha: float, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def alpha(self) -> float: ...
    @property
    def lower(self): ...
    @property
    def min(self) -> float: ...
    @property
    def upper(self): ...

class TruncatedRayleigh(Distribution):
    def __init__(self, scale: float, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
    @property
    def lower(self): ...
    @property
    def scale(self): ...
    @property
    def upper(self): ...

class Uniform(Distribution):
    lower: Incomplete
    upper: Incomplete
    def __init__(self, lower: float, upper: float) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...

class UniformAngle(Distribution):
    def __init__(self) -> None: ...
    def cdf(self, x: float) -> float: ...
    def logpdf(self, x: float) -> float: ...
    def ppf(self, q: float) -> float: ...
