name: 51Peg

on:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    #   - main

jobs:
  build:
    name: Build with pip
    runs-on: ${{ matrix.platform }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        # python-version: ["3.8", "3.9", "3.10", "3.11"]
        python-version: ["3.10"]
        experimental: [false]
        include:
          - platform: windows-latest
            python-version: "3.11"
            experimental: true

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV

    - name: Requirements for development
      run: |
        pip install pip -U
        pip install wheel nanobind "scikit-build-core[pyproject]" -U

    - name: Build and install
      run: |
        pip install --no-build-isolation -Ceditable.rebuild=true -ve .

    - name: Import
      run: |
        python -c "import kima"

    - name: Run 51Peg example
      run : |
        python -c "from kima.examples._51Peg import _51Peg; model = _51Peg(run=True, steps=100)"
