name: Build and upload to PyPI

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build_wheels:
    name: wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          # Needed for full C++17 support
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET='10.15'
          # CIBW_BUILD: ${{ matrix.py }}*
          # CIBW_ARCHS: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build sdist
        run: pipx run build --sdist

      - name: Tilde
        run: |
          python metadata_tilde.py dist

      - uses: actions/upload-artifact@v7
        with:
          name: sdist
          path: dist/*.tar.gz


  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: deploy-to-pypi
      url: https://pypi.org/p/kima
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Test downloaded artifacts
        run: |
          ls dist/*

      - name: Flatten artifact directories
        run: |
          mkdir final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;
          find dist -name "*.tar.gz" -exec cp {} final_dist/ \;

      - name: Check 
        run: pipx run twine check final_dist/*.whl --strict

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   # with:
      #   #   repository-url: https://test.pypi.org/legacy/
